### ISSUE TITLE
issues with running most scripts based on file dependency locations

### ISSUE THREAD

**Issue by jaw2ay** [IOActive/laf#17]
I want to set up the db locally, attempted to run Packetforwader.py 
I get this error
Traceback (most recent call last):
  File "PacketForwarderCollector.py", line 7, in <module>
    from auditing.datacollectors.utils.PacketPersistence import save
  File "/home/jack/laf/auditing/datacollectors/utils/PacketPersistence.py", line 2, in <module>
    import auditing.db.Service as db_service
  File "/home/jack/laf/auditing/db/__init__.py", line 16, in <module>
    DB_HOST = os.environ["DB_HOST"] 
  File "/usr/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'DB_HOST'

I cant seem to find an easy way to build the DB schema.  Is there a quick solution for this locally?

**Comment by matiassequeira** [comment]
Hello, sorry for the delay. A couple of questions:

* Are you using the tool locally, or with Docker?
* If trying to run it without Docker, are you trying to use Postgres or SQLite?

I highly recommend you using Docker, since it requires less configuration.
